// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: jobqueue_outbox.writer.sql

package xsqlc

import (
	"context"
)

const createOutboxItem = `-- name: CreateOutboxItem :one
INSERT INTO outbox_items (id, idempotent_key, "status", job_type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateOutboxItemParams struct {
	ID            string
	IdempotentKey string
	Status        string
	JobType       string
	Payload       string
}

func (q *Queries) CreateOutboxItem(ctx context.Context, arg CreateOutboxItemParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createOutboxItem,
		arg.ID,
		arg.IdempotentKey,
		arg.Status,
		arg.JobType,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
